---
#Install php
- name: Install PHP-FPM
  apt: name=php5-fpm state=latest update-cache=yes
  sudo: yes

- name: Install PHP packages
  apt: pkg={{item}} state=latest update-cache=yes
  with_items: $php_packages
  notify:
    - restart php5-fpm