---
#Install php
- name: Install PHP-FPM
  apt: name=php5-fpm state=latest update-cache=yes
  sudo: yes

- name: Install PHP packages
  apt: pkg={{item}} state=latest update-cache=yes
  with_items: $php_packages
  notify:
    - restart php5-fpm

- name: Configure php.ini
  ini_file: dest=/etc/php5/fpm/php.ini 
            section={{ item.section }}
            option={{ item. option }}
            value={{ item.value }}
  with_items: $php_ini
  notify:
    - restart php5-fpm